# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'generate.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1220, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1220, 720))
        MainWindow.setMaximumSize(QtCore.QSize(1220, 720))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/main.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 490, 641, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton.setChecked(True)
        self.radioButton.setAutoRepeat(False)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_0 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_0.setObjectName("radioButton_0")
        self.horizontalLayout.addWidget(self.radioButton_0)
        self.radioButton_1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_1.setObjectName("radioButton_1")
        self.horizontalLayout.addWidget(self.radioButton_1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout.addWidget(self.radioButton_6)
        self.radioButton_7 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_7.setObjectName("radioButton_7")
        self.horizontalLayout.addWidget(self.radioButton_7)
        self.radioButton_8 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_8.setObjectName("radioButton_8")
        self.horizontalLayout.addWidget(self.radioButton_8)
        self.radioButton_9 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_9.setObjectName("radioButton_9")
        self.horizontalLayout.addWidget(self.radioButton_9)
        self.radioButton_10 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_10.setObjectName("radioButton_10")
        self.horizontalLayout.addWidget(self.radioButton_10)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.label.setStyleSheet("background-color: rgba(255, 255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(170, 530, 160, 120))
        self.label_1.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 530, 160, 120))
        self.label_2.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(490, 530, 160, 120))
        self.label_3.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 530, 80, 60))
        self.label_4.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_0 = QtWidgets.QLabel(self.centralwidget)
        self.label_0.setGeometry(QtCore.QRect(10, 530, 160, 120))
        self.label_0.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_0.setText("")
        self.label_0.setObjectName("label_0")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 590, 80, 60))
        self.label_5.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(730, 530, 80, 60))
        self.label_6.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_0.setGeometry(QtCore.QRect(10, 530, 160, 120))
        self.pushButton_0.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_0.setText("")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(170, 530, 160, 120))
        self.pushButton_1.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_1.setText("")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(490, 530, 160, 120))
        self.pushButton_3.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(650, 530, 80, 60))
        self.pushButton_4.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 530, 160, 120))
        self.pushButton_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(650, 590, 80, 60))
        self.pushButton_5.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(730, 530, 80, 60))
        self.pushButton_6.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(730, 590, 80, 60))
        self.label_7.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(810, 530, 80, 60))
        self.label_8.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(810, 590, 80, 60))
        self.label_9.setStyleSheet("background-color: rgba(250, 255, 255,150);")
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(730, 590, 80, 60))
        self.pushButton_7.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(810, 530, 80, 60))
        self.pushButton_8.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(810, 590, 80, 60))
        self.pushButton_9.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
                                        "")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(900, 530, 271, 111))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_42 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_2.addWidget(self.pushButton_42, 2, 0, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_2.addWidget(self.pushButton_40, 1, 0, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_2.addWidget(self.pushButton_38, 0, 0, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_43.setText("")
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_2.addWidget(self.pushButton_43, 2, 1, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_41.setText("")
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout_2.addWidget(self.pushButton_41, 1, 1, 1, 1)
        self.formLayout_14 = QtWidgets.QFormLayout()
        self.formLayout_14.setObjectName("formLayout_14")
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_19.setStyleSheet("")
        self.label_19.setObjectName("label_19")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.doubleSpinBox_23.setStyleSheet("")
        self.doubleSpinBox_23.setAccelerated(True)
        self.doubleSpinBox_23.setDecimals(0)
        self.doubleSpinBox_23.setMinimum(0.0)
        self.doubleSpinBox_23.setMaximum(100.0)
        self.doubleSpinBox_23.setSingleStep(1.0)
        self.doubleSpinBox_23.setProperty("value", 80.0)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.formLayout_14.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_23)
        self.gridLayout_2.addLayout(self.formLayout_14, 0, 1, 1, 1)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(660, 10, 540, 520))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_1 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_1.setObjectName("gridLayout_1")
        self.pushButton_34 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_34.setStyleSheet("")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_1.addWidget(self.pushButton_34, 10, 2, 1, 1)
        self.formLayout_8 = QtWidgets.QFormLayout()
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_19.setStyleSheet("")
        self.doubleSpinBox_19.setAccelerated(True)
        self.doubleSpinBox_19.setDecimals(0)
        self.doubleSpinBox_19.setMinimum(0.0)
        self.doubleSpinBox_19.setMaximum(200.0)
        self.doubleSpinBox_19.setSingleStep(1.0)
        self.doubleSpinBox_19.setProperty("value", 10.0)
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_19)
        self.gridLayout_1.addLayout(self.formLayout_8, 16, 3, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_11.setStyleSheet("")
        self.doubleSpinBox_11.setAccelerated(True)
        self.doubleSpinBox_11.setDecimals(0)
        self.doubleSpinBox_11.setMaximum(1000.0)
        self.doubleSpinBox_11.setSingleStep(1.0)
        self.doubleSpinBox_11.setProperty("value", 50.0)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.doubleSpinBox_11)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_12.setStyleSheet("")
        self.doubleSpinBox_12.setAccelerated(True)
        self.doubleSpinBox_12.setDecimals(0)
        self.doubleSpinBox_12.setMaximum(1000.0)
        self.doubleSpinBox_12.setSingleStep(1.0)
        self.doubleSpinBox_12.setProperty("value", 240.0)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_12)
        self.gridLayout_1.addLayout(self.formLayout, 8, 3, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_32.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                         "")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_1.addWidget(self.pushButton_32, 6, 2, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_35.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                         "")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_1.addWidget(self.pushButton_35, 11, 2, 1, 1)
        self.doubleSpinBox_0 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_0.setAccelerated(True)
        self.doubleSpinBox_0.setDecimals(0)
        self.doubleSpinBox_0.setMaximum(255.0)
        self.doubleSpinBox_0.setSingleStep(1.0)
        self.doubleSpinBox_0.setProperty("value", 127.0)
        self.doubleSpinBox_0.setObjectName("doubleSpinBox_0")
        self.gridLayout_1.addWidget(self.doubleSpinBox_0, 6, 1, 1, 1)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_16.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                            "")
        self.doubleSpinBox_16.setAccelerated(True)
        self.doubleSpinBox_16.setDecimals(0)
        self.doubleSpinBox_16.setMinimum(0.0)
        self.doubleSpinBox_16.setMaximum(10000.0)
        self.doubleSpinBox_16.setSingleStep(1.0)
        self.doubleSpinBox_16.setProperty("value", 100.0)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_16)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                    "")
        self.label_12.setObjectName("label_12")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.gridLayout_1.addLayout(self.formLayout_4, 13, 3, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_1.addWidget(self.pushButton_16, 6, 0, 1, 1)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                    "")
        self.label_11.setObjectName("label_11")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_13.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                            "")
        self.doubleSpinBox_13.setAccelerated(True)
        self.doubleSpinBox_13.setDecimals(0)
        self.doubleSpinBox_13.setMinimum(1.0)
        self.doubleSpinBox_13.setMaximum(49.0)
        self.doubleSpinBox_13.setSingleStep(2.0)
        self.doubleSpinBox_13.setProperty("value", 3.0)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_13)
        self.gridLayout_1.addLayout(self.formLayout_3, 11, 3, 1, 1)
        self.formLayout_10 = QtWidgets.QFormLayout()
        self.formLayout_10.setObjectName("formLayout_10")
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                    "")
        self.label_20.setObjectName("label_20")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.doubleSpinBox_20 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_20.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                            "")
        self.doubleSpinBox_20.setAccelerated(True)
        self.doubleSpinBox_20.setDecimals(0)
        self.doubleSpinBox_20.setMinimum(1.0)
        self.doubleSpinBox_20.setMaximum(50.0)
        self.doubleSpinBox_20.setSingleStep(1.0)
        self.doubleSpinBox_20.setProperty("value", 2.0)
        self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_20)
        self.gridLayout_1.addLayout(self.formLayout_10, 18, 3, 1, 1)
        self.formLayout_9 = QtWidgets.QFormLayout()
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                    "")
        self.label_17.setObjectName("label_17")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_21.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                            "")
        self.doubleSpinBox_21.setAccelerated(True)
        self.doubleSpinBox_21.setDecimals(3)
        self.doubleSpinBox_21.setMinimum(0.04)
        self.doubleSpinBox_21.setMaximum(0.06)
        self.doubleSpinBox_21.setSingleStep(0.001)
        self.doubleSpinBox_21.setProperty("value", 0.04)
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_21)
        self.gridLayout_1.addLayout(self.formLayout_9, 19, 2, 1, 1)
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_14.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                            "")
        self.doubleSpinBox_14.setAccelerated(True)
        self.doubleSpinBox_14.setDecimals(0)
        self.doubleSpinBox_14.setMinimum(0.0)
        self.doubleSpinBox_14.setMaximum(10000.0)
        self.doubleSpinBox_14.setSingleStep(1.0)
        self.doubleSpinBox_14.setProperty("value", 50.0)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_14)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                    "")
        self.label_13.setObjectName("label_13")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.gridLayout_1.addLayout(self.formLayout_5, 12, 3, 1, 1)
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_4.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                      "")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.comboBox_4)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_10.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                            "")
        self.doubleSpinBox_10.setAccelerated(True)
        self.doubleSpinBox_10.setDecimals(0)
        self.doubleSpinBox_10.setMinimum(1.0)
        self.doubleSpinBox_10.setMaximum(49.0)
        self.doubleSpinBox_10.setSingleStep(2.0)
        self.doubleSpinBox_10.setProperty("value", 3.0)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_10)
        self.gridLayout_1.addLayout(self.formLayout_2, 6, 3, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_36.setStyleSheet("")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_1.addWidget(self.pushButton_36, 14, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_1.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.formLayout_11 = QtWidgets.QFormLayout()
        self.formLayout_11.setObjectName("formLayout_11")
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                    "")
        self.label_21.setObjectName("label_21")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_22.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                            "")
        self.doubleSpinBox_22.setAccelerated(True)
        self.doubleSpinBox_22.setDecimals(0)
        self.doubleSpinBox_22.setMinimum(1.0)
        self.doubleSpinBox_22.setMaximum(31.0)
        self.doubleSpinBox_22.setSingleStep(2.0)
        self.doubleSpinBox_22.setProperty("value", 3.0)
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.formLayout_11.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_22)
        self.gridLayout_1.addLayout(self.formLayout_11, 19, 3, 1, 1)
        self.formLayout_7 = QtWidgets.QFormLayout()
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_17.setStyleSheet("")
        self.doubleSpinBox_17.setAccelerated(True)
        self.doubleSpinBox_17.setDecimals(0)
        self.doubleSpinBox_17.setMinimum(0.0)
        self.doubleSpinBox_17.setMaximum(10000.0)
        self.doubleSpinBox_17.setSingleStep(1.0)
        self.doubleSpinBox_17.setProperty("value", 50.0)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_17)
        self.gridLayout_1.addLayout(self.formLayout_7, 14, 3, 1, 1)
        self.comboBox_7 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_7.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                      "")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.gridLayout_1.addWidget(self.comboBox_7, 12, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_1.addWidget(self.pushButton_12, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setTabletTracking(False)
        self.checkBox.setAcceptDrops(False)
        self.checkBox.setChecked(False)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_1.addWidget(self.checkBox, 0, 3, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_1.addWidget(self.pushButton_10, 0, 0, 1, 1)
        self.formLayout_13 = QtWidgets.QFormLayout()
        self.formLayout_13.setObjectName("formLayout_13")
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_5.setStyleSheet("")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.comboBox_5)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_6.setStyleSheet("")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_6)
        self.gridLayout_1.addLayout(self.formLayout_13, 10, 3, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_1.addWidget(self.pushButton_26, 0, 2, 1, 1)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_18.setStyleSheet("")
        self.doubleSpinBox_18.setAccelerated(True)
        self.doubleSpinBox_18.setDecimals(0)
        self.doubleSpinBox_18.setMinimum(0.0)
        self.doubleSpinBox_18.setMaximum(500.0)
        self.doubleSpinBox_18.setSingleStep(1.0)
        self.doubleSpinBox_18.setProperty("value", 90.0)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_18)
        self.gridLayout_1.addLayout(self.formLayout_6, 16, 2, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_37.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                         "")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_1.addWidget(self.pushButton_37, 18, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_1.addWidget(self.pushButton_13, 1, 1, 1, 1)
        self.formLayout_12 = QtWidgets.QFormLayout()
        self.formLayout_12.setObjectName("formLayout_12")
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_15.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                            "")
        self.doubleSpinBox_15.setAccelerated(True)
        self.doubleSpinBox_15.setDecimals(0)
        self.doubleSpinBox_15.setMinimum(0.0)
        self.doubleSpinBox_15.setMaximum(200000000.0)
        self.doubleSpinBox_15.setSingleStep(1.0)
        self.doubleSpinBox_15.setProperty("value", 20.0)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBox_15)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                    "")
        self.label_18.setObjectName("label_18")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.gridLayout_1.addLayout(self.formLayout_12, 13, 2, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_1.addWidget(self.pushButton_29, 4, 2, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_1.addWidget(self.pushButton_30, 4, 3, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_1.addWidget(self.pushButton_27, 1, 2, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_1.addWidget(self.pushButton_28, 1, 3, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_31.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                         "")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_1.addWidget(self.pushButton_31, 5, 2, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setStyleSheet("background-color: rgba(170, 170, 255, 120);\n"
                                      "")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_1.addWidget(self.comboBox_3, 5, 3, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_33.setStyleSheet("")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_1.addWidget(self.pushButton_33, 8, 2, 1, 1)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_9.setAccelerated(True)
        self.doubleSpinBox_9.setDecimals(1)
        self.doubleSpinBox_9.setMinimum(0.1)
        self.doubleSpinBox_9.setMaximum(10.0)
        self.doubleSpinBox_9.setSingleStep(0.1)
        self.doubleSpinBox_9.setProperty("value", 1.0)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.gridLayout_1.addWidget(self.doubleSpinBox_9, 19, 1, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_1.addWidget(self.pushButton_25, 19, 0, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_1.addWidget(self.pushButton_24, 18, 0, 1, 1)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_8.setAccelerated(True)
        self.doubleSpinBox_8.setDecimals(0)
        self.doubleSpinBox_8.setMinimum(-360.0)
        self.doubleSpinBox_8.setMaximum(360.0)
        self.doubleSpinBox_8.setSingleStep(1.0)
        self.doubleSpinBox_8.setProperty("value", 0.0)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.gridLayout_1.addWidget(self.doubleSpinBox_8, 18, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_1.addWidget(self.pushButton_23, 16, 0, 1, 1)
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_7.setAccelerated(True)
        self.doubleSpinBox_7.setDecimals(0)
        self.doubleSpinBox_7.setMinimum(1.0)
        self.doubleSpinBox_7.setMaximum(1000.0)
        self.doubleSpinBox_7.setSingleStep(1.0)
        self.doubleSpinBox_7.setProperty("value", 5.0)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.gridLayout_1.addWidget(self.doubleSpinBox_7, 16, 1, 1, 1)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_6.setAccelerated(True)
        self.doubleSpinBox_6.setDecimals(0)
        self.doubleSpinBox_6.setMinimum(1.0)
        self.doubleSpinBox_6.setMaximum(1000.0)
        self.doubleSpinBox_6.setSingleStep(1.0)
        self.doubleSpinBox_6.setProperty("value", 5.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.gridLayout_1.addWidget(self.doubleSpinBox_6, 14, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_1.addWidget(self.pushButton_22, 14, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_1.addWidget(self.pushButton_21, 13, 0, 1, 1)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_5.setAccelerated(True)
        self.doubleSpinBox_5.setDecimals(0)
        self.doubleSpinBox_5.setMinimum(1.0)
        self.doubleSpinBox_5.setMaximum(1000.0)
        self.doubleSpinBox_5.setSingleStep(1.0)
        self.doubleSpinBox_5.setProperty("value", 5.0)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.gridLayout_1.addWidget(self.doubleSpinBox_5, 13, 1, 1, 1)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_4.setAccelerated(True)
        self.doubleSpinBox_4.setDecimals(0)
        self.doubleSpinBox_4.setMinimum(1.0)
        self.doubleSpinBox_4.setMaximum(100.0)
        self.doubleSpinBox_4.setSingleStep(1.0)
        self.doubleSpinBox_4.setProperty("value", 3.0)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.gridLayout_1.addWidget(self.doubleSpinBox_4, 12, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_1.addWidget(self.pushButton_20, 12, 0, 1, 1)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_3.setAccelerated(True)
        self.doubleSpinBox_3.setDecimals(0)
        self.doubleSpinBox_3.setMinimum(1.0)
        self.doubleSpinBox_3.setMaximum(100.0)
        self.doubleSpinBox_3.setSingleStep(1.0)
        self.doubleSpinBox_3.setProperty("value", 3.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.gridLayout_1.addWidget(self.doubleSpinBox_3, 11, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_1.addWidget(self.pushButton_19, 11, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_1.addWidget(self.pushButton_18, 10, 0, 1, 1)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_2.setAccelerated(True)
        self.doubleSpinBox_2.setDecimals(0)
        self.doubleSpinBox_2.setMinimum(1.0)
        self.doubleSpinBox_2.setMaximum(30.0)
        self.doubleSpinBox_2.setSingleStep(1.0)
        self.doubleSpinBox_2.setProperty("value", 2.0)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.gridLayout_1.addWidget(self.doubleSpinBox_2, 10, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_1.addWidget(self.pushButton_17, 8, 0, 1, 1)
        self.doubleSpinBox_1 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
        self.doubleSpinBox_1.setAccelerated(True)
        self.doubleSpinBox_1.setDecimals(0)
        self.doubleSpinBox_1.setMinimum(1.0)
        self.doubleSpinBox_1.setMaximum(30.0)
        self.doubleSpinBox_1.setSingleStep(1.0)
        self.doubleSpinBox_1.setProperty("value", 2.0)
        self.doubleSpinBox_1.setObjectName("doubleSpinBox_1")
        self.gridLayout_1.addWidget(self.doubleSpinBox_1, 8, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_1.addWidget(self.pushButton_15, 5, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_1.addWidget(self.comboBox_2, 5, 1, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.gridLayout_1.addWidget(self.comboBox_1, 4, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_1.addWidget(self.pushButton_14, 4, 0, 1, 1)
        self.label_9.raise_()
        self.label_3.raise_()
        self.label_8.raise_()
        self.label_6.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_7.raise_()
        self.label_4.raise_()
        self.label_0.raise_()
        self.label_1.raise_()
        self.pushButton_4.raise_()
        self.pushButton_7.raise_()
        self.pushButton_0.raise_()
        self.pushButton_8.raise_()
        self.pushButton_3.raise_()
        self.pushButton_2.raise_()
        self.pushButton_1.raise_()
        self.pushButton_9.raise_()
        self.pushButton_6.raise_()
        self.pushButton_5.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label.raise_()
        self.gridLayoutWidget_2.raise_()
        self.gridLayoutWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1220, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox_4.setCurrentIndex(1)
        self.comboBox_7.setCurrentIndex(1)
        self.comboBox_5.setCurrentIndex(0)
        self.comboBox_6.setCurrentIndex(0)
        self.comboBox_3.setCurrentIndex(1)
        self.comboBox_2.setCurrentIndex(0)
        self.comboBox_1.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pushButton_10, self.pushButton_11)
        MainWindow.setTabOrder(self.pushButton_11, self.pushButton_26)
        MainWindow.setTabOrder(self.pushButton_26, self.checkBox)
        MainWindow.setTabOrder(self.checkBox, self.pushButton_12)
        MainWindow.setTabOrder(self.pushButton_12, self.pushButton_13)
        MainWindow.setTabOrder(self.pushButton_13, self.pushButton_14)
        MainWindow.setTabOrder(self.pushButton_14, self.comboBox_1)
        MainWindow.setTabOrder(self.comboBox_1, self.pushButton_15)
        MainWindow.setTabOrder(self.pushButton_15, self.comboBox_2)
        MainWindow.setTabOrder(self.comboBox_2, self.pushButton_16)
        MainWindow.setTabOrder(self.pushButton_16, self.doubleSpinBox_0)
        MainWindow.setTabOrder(self.doubleSpinBox_0, self.pushButton_17)
        MainWindow.setTabOrder(self.pushButton_17, self.doubleSpinBox_1)
        MainWindow.setTabOrder(self.doubleSpinBox_1, self.pushButton_18)
        MainWindow.setTabOrder(self.pushButton_18, self.doubleSpinBox_2)
        MainWindow.setTabOrder(self.doubleSpinBox_2, self.pushButton_19)
        MainWindow.setTabOrder(self.pushButton_19, self.doubleSpinBox_3)
        MainWindow.setTabOrder(self.doubleSpinBox_3, self.pushButton_20)
        MainWindow.setTabOrder(self.pushButton_20, self.doubleSpinBox_4)
        MainWindow.setTabOrder(self.doubleSpinBox_4, self.pushButton_21)
        MainWindow.setTabOrder(self.pushButton_21, self.doubleSpinBox_5)
        MainWindow.setTabOrder(self.doubleSpinBox_5, self.pushButton_22)
        MainWindow.setTabOrder(self.pushButton_22, self.doubleSpinBox_6)
        MainWindow.setTabOrder(self.doubleSpinBox_6, self.pushButton_23)
        MainWindow.setTabOrder(self.pushButton_23, self.doubleSpinBox_7)
        MainWindow.setTabOrder(self.doubleSpinBox_7, self.pushButton_24)
        MainWindow.setTabOrder(self.pushButton_24, self.doubleSpinBox_8)
        MainWindow.setTabOrder(self.doubleSpinBox_8, self.pushButton_25)
        MainWindow.setTabOrder(self.pushButton_25, self.doubleSpinBox_9)
        MainWindow.setTabOrder(self.doubleSpinBox_9, self.pushButton_27)
        MainWindow.setTabOrder(self.pushButton_27, self.pushButton_28)
        MainWindow.setTabOrder(self.pushButton_28, self.pushButton_29)
        MainWindow.setTabOrder(self.pushButton_29, self.pushButton_30)
        MainWindow.setTabOrder(self.pushButton_30, self.pushButton_31)
        MainWindow.setTabOrder(self.pushButton_31, self.comboBox_3)
        MainWindow.setTabOrder(self.comboBox_3, self.pushButton_32)
        MainWindow.setTabOrder(self.pushButton_32, self.comboBox_4)
        MainWindow.setTabOrder(self.comboBox_4, self.doubleSpinBox_10)
        MainWindow.setTabOrder(self.doubleSpinBox_10, self.pushButton_33)
        MainWindow.setTabOrder(self.pushButton_33, self.doubleSpinBox_11)
        MainWindow.setTabOrder(self.doubleSpinBox_11, self.doubleSpinBox_12)
        MainWindow.setTabOrder(self.doubleSpinBox_12, self.pushButton_34)
        MainWindow.setTabOrder(self.pushButton_34, self.comboBox_5)
        MainWindow.setTabOrder(self.comboBox_5, self.comboBox_6)
        MainWindow.setTabOrder(self.comboBox_6, self.pushButton_35)
        MainWindow.setTabOrder(self.pushButton_35, self.doubleSpinBox_13)
        MainWindow.setTabOrder(self.doubleSpinBox_13, self.comboBox_7)
        MainWindow.setTabOrder(self.comboBox_7, self.doubleSpinBox_14)
        MainWindow.setTabOrder(self.doubleSpinBox_14, self.doubleSpinBox_15)
        MainWindow.setTabOrder(self.doubleSpinBox_15, self.doubleSpinBox_16)
        MainWindow.setTabOrder(self.doubleSpinBox_16, self.pushButton_36)
        MainWindow.setTabOrder(self.pushButton_36, self.doubleSpinBox_17)
        MainWindow.setTabOrder(self.doubleSpinBox_17, self.doubleSpinBox_18)
        MainWindow.setTabOrder(self.doubleSpinBox_18, self.doubleSpinBox_19)
        MainWindow.setTabOrder(self.doubleSpinBox_19, self.pushButton_37)
        MainWindow.setTabOrder(self.pushButton_37, self.doubleSpinBox_20)
        MainWindow.setTabOrder(self.doubleSpinBox_20, self.doubleSpinBox_21)
        MainWindow.setTabOrder(self.doubleSpinBox_21, self.doubleSpinBox_22)
        MainWindow.setTabOrder(self.doubleSpinBox_22, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.radioButton_0)
        MainWindow.setTabOrder(self.radioButton_0, self.radioButton_1)
        MainWindow.setTabOrder(self.radioButton_1, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.radioButton_4)
        MainWindow.setTabOrder(self.radioButton_4, self.radioButton_5)
        MainWindow.setTabOrder(self.radioButton_5, self.radioButton_6)
        MainWindow.setTabOrder(self.radioButton_6, self.radioButton_7)
        MainWindow.setTabOrder(self.radioButton_7, self.radioButton_8)
        MainWindow.setTabOrder(self.radioButton_8, self.radioButton_9)
        MainWindow.setTabOrder(self.radioButton_9, self.radioButton_10)
        MainWindow.setTabOrder(self.radioButton_10, self.pushButton_0)
        MainWindow.setTabOrder(self.pushButton_0, self.pushButton_1)
        MainWindow.setTabOrder(self.pushButton_1, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.pushButton_38)
        MainWindow.setTabOrder(self.pushButton_38, self.pushButton_40)
        MainWindow.setTabOrder(self.pushButton_40, self.pushButton_42)
        MainWindow.setTabOrder(self.pushButton_42, self.pushButton_41)
        MainWindow.setTabOrder(self.pushButton_41, self.pushButton_43)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "图片处理"))
        self.radioButton.setText(_translate("MainWindow", "原图"))
        self.radioButton_0.setText(_translate("MainWindow", "Gray"))
        self.radioButton_1.setText(_translate("MainWindow", "B"))
        self.radioButton_2.setText(_translate("MainWindow", "G"))
        self.radioButton_3.setText(_translate("MainWindow", "R"))
        self.radioButton_4.setText(_translate("MainWindow", "H"))
        self.radioButton_5.setText(_translate("MainWindow", "S"))
        self.radioButton_6.setText(_translate("MainWindow", "V"))
        self.radioButton_7.setText(_translate("MainWindow", "L"))
        self.radioButton_8.setText(_translate("MainWindow", "A"))
        self.radioButton_9.setText(_translate("MainWindow", "B"))
        self.radioButton_10.setText(_translate("MainWindow", "All"))
        self.pushButton_42.setText(_translate("MainWindow", "全景合成"))
        self.pushButton_40.setText(_translate("MainWindow", "视频提取"))
        self.pushButton_38.setText(_translate("MainWindow", "模板匹配"))
        self.label_19.setText(_translate("MainWindow", "相似度(%)"))
        self.pushButton_34.setText(_translate("MainWindow", "轮廓检测"))
        self.label_16.setText(_translate("MainWindow", "最大断裂"))
        self.pushButton_32.setText(_translate("MainWindow", "图像模糊"))
        self.pushButton_35.setText(_translate("MainWindow", "霍夫圆形检测"))
        self.label_12.setText(_translate("MainWindow", "最大半径"))
        self.pushButton_16.setText(_translate("MainWindow", "二值化"))
        self.label_11.setText(_translate("MainWindow", "模糊"))
        self.label_20.setText(_translate("MainWindow", "区块大小"))
        self.label_17.setText(_translate("MainWindow", "自由值"))
        self.label_13.setText(_translate("MainWindow", "最小半径"))
        self.comboBox_4.setCurrentText(_translate("MainWindow", "高斯模糊"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "均值模糊"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "高斯模糊"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "中值模糊"))
        self.pushButton_36.setText(_translate("MainWindow", "霍夫直线检测"))
        self.pushButton_11.setText(_translate("MainWindow", "保存图片"))
        self.label_21.setText(_translate("MainWindow", "卷积核"))
        self.label_15.setText(_translate("MainWindow", "最小长度"))
        self.comboBox_7.setCurrentText(_translate("MainWindow", "最优圆"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "全部圆"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "最优圆"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "2个圆"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "3个圆"))
        self.pushButton_12.setText(_translate("MainWindow", "显示原图"))
        self.checkBox.setText(_translate("MainWindow", "操作叠加"))
        self.pushButton_10.setText(_translate("MainWindow", "打开图片"))
        self.comboBox_5.setCurrentText(_translate("MainWindow", "绘制边沿"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "绘制边沿"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "外接矩形"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "外接椭圆"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "外接圆"))
        self.comboBox_6.setCurrentText(_translate("MainWindow", "原图"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "原图"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "新图"))
        self.pushButton_26.setText(_translate("MainWindow", "清空图片"))
        self.label_14.setText(_translate("MainWindow", "曲线交点数"))
        self.pushButton_37.setText(_translate("MainWindow", "角点检测(Harris)"))
        self.pushButton_13.setText(_translate("MainWindow", "置入当前图"))
        self.label_18.setText(_translate("MainWindow", "圆心距"))
        self.pushButton_29.setText(_translate("MainWindow", "阈值翻转"))
        self.pushButton_30.setText(_translate("MainWindow", "显示差异"))
        self.pushButton_27.setText(_translate("MainWindow", "彩色直方图均衡化"))
        self.pushButton_28.setText(_translate("MainWindow", "灰度直方图均衡化"))
        self.pushButton_31.setText(_translate("MainWindow", "锐化"))
        self.comboBox_3.setCurrentText(_translate("MainWindow", "平滑"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "锐利"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "平滑"))
        self.pushButton_33.setText(_translate("MainWindow", "边沿检测(Edge)"))
        self.pushButton_25.setText(_translate("MainWindow", "图像缩放"))
        self.pushButton_24.setText(_translate("MainWindow", "图像旋转"))
        self.pushButton_23.setText(_translate("MainWindow", "黑帽运算"))
        self.pushButton_22.setText(_translate("MainWindow", "顶帽运算"))
        self.pushButton_21.setText(_translate("MainWindow", "形态梯度"))
        self.pushButton_20.setText(_translate("MainWindow", "闭运算"))
        self.pushButton_19.setText(_translate("MainWindow", "开运算"))
        self.pushButton_18.setText(_translate("MainWindow", "膨胀"))
        self.pushButton_17.setText(_translate("MainWindow", "腐蚀"))
        self.pushButton_15.setText(_translate("MainWindow", "自适应二值化"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "标准自适应"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "高斯自适应"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "均值自适应"))
        self.comboBox_1.setCurrentText(_translate("MainWindow", "左右镜像"))
        self.comboBox_1.setItemText(0, _translate("MainWindow", "上下镜像"))
        self.comboBox_1.setItemText(1, _translate("MainWindow", "左右镜像"))
        self.pushButton_14.setText(_translate("MainWindow", "图像翻转"))
